### ISSUE TITLE
Dataset link is not accessible

### ISSUE THREAD

**Issue by mutazmq** [rkadlec/ubuntu-ranking-dataset-creator#11]
Can't download the dataset. The [link](http://cs.mcgill.ca/~jpineau/datasets/ubuntu-corpus-1.0/ubuntu_dialogs.tgz)  is not accessible

**Comment by avostryakov** [comment]
The same for me :(

**Comment by rkadlec** [comment]
The source data is hosted at McGill university. Unfortunately I can't directly fix it.  
@ryan-lowe Do you know what is happening? Can you fix it?

**Comment by ryan-lowe** [comment]
@rkadlec It seems to be a problem with the McGill servers. The files are on the server (and smaller files are visible), but the connection gets dropped for larger files such as the Ubuntu dataset (on both Joelle's and Nissan's site). 

We're coordinating with the McGill CS tech support crew -- hopefully this should be fixed shortly!

**Comment by rkadlec** [comment]
@ryan-lowe I tried it today  and it still doesn't work. Do you think that it would be possible to move the datasets to some public file sharing server?

**Comment by avostryakov** [comment]
I could download it a week ago. It's worked recently.

**Comment by rkadlec** [comment]
You are right. I tested it today with link provided by @mutazmq in the initial post and it failed. However, it downloads ok when I run the script. I am closing this issue.
